// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UlIXUFokJUj2hYJpwSVHkgSE3bgPQYI',
    appId: '1:389058299944:web:eb290a4e7f49de51bdcd1d',
    messagingSenderId: '389058299944',
    projectId: 'helep2',
    authDomain: 'helep2.firebaseapp.com',
    storageBucket: 'helep2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGNfE7fo-HOi03oEd_AdcGjmJDX7Y3GbY',
    appId: '1:389058299944:android:8c49fc875dbcecefbdcd1d',
    messagingSenderId: '389058299944',
    projectId: 'helep2',
    storageBucket: 'helep2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmNY-j8M2kCBTIC_rMycYf5DeWz0k_25s',
    appId: '1:389058299944:ios:823dee1157d811c1bdcd1d',
    messagingSenderId: '389058299944',
    projectId: 'helep2',
    storageBucket: 'helep2.appspot.com',
    iosBundleId: 'com.example.helepV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmNY-j8M2kCBTIC_rMycYf5DeWz0k_25s',
    appId: '1:389058299944:ios:1685c8b4f68dad8ebdcd1d',
    messagingSenderId: '389058299944',
    projectId: 'helep2',
    storageBucket: 'helep2.appspot.com',
    iosBundleId: 'com.example.helepV1.RunnerTests',
  );
}
